
site_name: Documentation
theme:
  name: material
plugins:
  - search
  - mermaid2
  - plantuml_markdown
  - pdf-export

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

# Add configurations for PDF generation including TOC and index
extra:
  pdf_export:
    toc: true
    index: true

# Add support for arc42 documentation structure

nav: !include nav.yml

    